mongodb:
  host: 'localhost'
  port: 27017
  database: 'loosemonkies_dev'

mysql:
    host: '127.0.0.1'
    port: 3306
    user: root
    pass: 123456
    db: lm_service

web_endpoint:
    host: 'http://www.loosemonkies.dev'

service_endpoint:
    host: 'http://api.loosemonkies.local'
