parameters:

    #### Services ####
    controller_listener.class: Loosemonkies\Bundle\CoreBundle\EventListener\ControllerListener

    #### Repositories ####

    phone_repository.class: Loosemonkies\Bundle\CoreBundle\Repository\PhoneRepository
    phone_list_repository.class: Loosemonkies\Bundle\CoreBundle\Repository\PhoneListRepository

services:

    #### Services ####

    controller_listener:
        class: %controller_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    #### Repositories ####

    phone_list_repository:
        class: %phone_list_repository.class%
        factory_service: doctrine_mongodb.odm.document_manager
        factory_method: getRepository
        arguments:
            - 'LoosemonkiesCoreBundle:PhoneList'

    phone_repository:
        class: %phone_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - 'LoosemonkiesCoreBundle:Phone'

